name: Build TankVectors

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Используем msbuild для восстановления, это надежнее для .NET 4.8
    - name: Restore NuGet Packages
      run: msbuild TankVectors.csproj -t:restore

    - name: Build TankVectors
      run: msbuild TankVectors.csproj /p:Configuration=Release

    - name: Upload TankVectors DLL
      uses: actions/upload-artifact@v4
      with:
        name: TankVectors-Release
        # Убран /net48/, так как мы отключили его в .csproj
        path: bin/Release/TankVectors.dll
